// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmprestimoLivros.API.Entityes
{
    [Table("LIVRO")]
    public partial class Livro
    {
        public Livro()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("livroNome")]
        [StringLength(50)]
        public string LivroNome { get; set; }
        [Required]
        [Column("livroAutor")]
        [StringLength(200)]
        public string LivroAutor { get; set; }
        [Column("livroEditora")]
        [StringLength(200)]
        public string LivroEditora { get; set; }
        [Column("livroAnoPublicacao", TypeName = "datetime")]
        public DateTime? LivroAnoPublicacao { get; set; }
        [Column("livroEducao")]
        [StringLength(50)]
        public string LivroEducao { get; set; }

        [InverseProperty("LceIdLivroNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}